version: '3.8'

volumes:
  pgdata:
  static:
  media:

services:

  django:
    build:
      context: .
    ports:
      - '8000:8000'
    container_name: django
    env_file:
      - docker/env/.env.dev
    volumes:
      - ./:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      - redis
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py runserver 0.0.0.0:8000"

  nginx:
    container_name: nginx
    working_dir: /app
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Yekaterinburg
    volumes:
      - static:/app/static
      - media:/app/media
      - ./docker/nginx/dev/:/etc/nginx/conf.d:ro
    links:
      - django
    depends_on:
      - django

  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - docker/env/.env.dev
    environment:
      - TZ=Asia/Yekaterinburg
    expose:
      - 6379
    volumes:
      - ./docker/redis/data:/data

  celery-worker:
    build: .
    container_name: celery-worker
    restart: always
    env_file:
      - docker/env/.env.dev
    volumes:
      - ./:/app
      - media:/app/media
    command: celery -A sitemyfirst worker --loglevel=info --logfile=./docker/logs/celery-worker.log
    depends_on:
      - redis

  celery-beat:
      build: .
      container_name: celery-beat
      env_file:
          - docker/env/.env.dev
      depends_on:
          - redis
      command: celery -A sitemyfirst beat --loglevel=info --logfile=./docker/logs/celery-beat.log
      volumes:
          - media:/app/media
          - ./:/app